version: '3.8'

services:
  auth_service:
    build: ./auth
    container_name: auth_service
    ports:
      - "8082:8082"
    networks:
      - go-network
    restart: unless-stopped

  user_service:
    build: ./users
    container_name: user_service
    ports:
      - "8083:8083"
    networks:
      - go-network
    restart: unless-stopped

  social_service:
    build: ./social
    container_name: social_service
    ports:
      - "8084:8084"
    networks:
      - go-network
    restart: unless-stopped

  chat_service:
    build: ./chat
    container_name: chat_service
    ports:
      - "8085:8085"
    networks:
      - go-network
    restart: unless-stopped

  api-gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth_service
      - user_service
      - social_service
      - chat_service
    environment:
      - PORT=8080

networks:
  go-network:
    driver: bridge

volumes:
  go-cache: