version: '3.8'

services:
  api:
    build: ./auth
    container_name: auth_service
    ports:
      - "8082:8082"
    networks:
      - go-network
    restart: unless-stopped

networks:
  go-network:
    driver: bridge

volumes:
  go-cache: